### ISSUE TITLE
Mechanical Circuit Simulation

### ISSUE THREAD

**Issue by hrtlacek** [mph-/lcapy#108]
In the Documentation it says: "The mechanical analogue II (impedance analogue) is employed" and "his also means that **series combinations transform to parallel combinations** and vice-versa.".
However, the only way I can get things to work is if I exactly replace electrical components with their mechanical equivalents without any topological changes. Is this expected behavior, am i misunderstanding the documentation?

**Comment by mph-** [comment]
Yes, in hindsight this was a mistake.  I chose the mechanical analogue II (with force analogous to voltage) since I was modelling transducers at the time and this was the convention.  However, this is really confusing with a nodal based system since you need to draw the mechanical circuit with one topology and simulate it with another!

It probably makes more sense to switch to the other analogue (with force analogous to current).   This preserves the circuit topology.

I welcome any suggestions you might have.

BTW, did you remove the circuit example you submitted?  For this circuit there was no load and so the force was the same.

**Comment by hrtlacek** [comment]
yes, i completely changed my initial comment since I realized I just made a mistake that didn't have anything to do with mechanical simulation (same behavior with electrical components). Sorry for that.

I am super interested in the whole mechanical and acoustic analogy, but i am not an expert.
I am surprised that you say 'you have to draw with one topology and simulate with another'. Can you give literature/links on that topic? 
Do you mean  you are internally converting series to parallel etc before simulating?

**Comment by mph-** [comment]
Hi I've pushed a patch to switch to the other analog (the mobility analog).  It seems to work but I have not fully tested it.  This analog is more intuitive except that mechanical impedance is equivalent to electrical impedance.  But it has the advantage that the circuit topology does not need to change.

There is a goodish comparison at https://en.wikipedia.org/wiki/Mechanical%E2%80%93electrical_analogies

**Comment by mph-** [comment]
Oops, I meant to say that with the mobility analog, electrical impedance is not equivalent to mechanical impedance.
