### ISSUE TITLE
Compact over-and-under display of component reference designator and value

### ISSUE THREAD

**Issue by timchinowsky** [mph-/lcapy#120]
By default `lcapy` displays components with both a reference designator and a value in `refdes=value` format like

![Screenshot from 2023-12-21 09-25-20](https://github.com/mph-/lcapy/assets/5445541/346a8aa2-9241-4c21-bfa2-63c859ca896d)

Is it possible to configure the rendering so that the value is shown underneath the reference designator, without the equal sign, for a more compact display, for example
![Screenshot from 2023-12-21 09-30-12](https://github.com/mph-/lcapy/assets/5445541/fd891753-349c-409e-915a-1bfcbc67f054)

**Comment by mph-** [comment]
You can achieve this using the 'l' and 'a' attributes for each component but that is a nuisance.
It should be straightforward to add a label style.  The hard part is thinking up a name for each style.  Do you have any suggestions?

**Comment by timchinowsky** [comment]
Hmm... how about "=" and "stacked"?  Or "h" and "v" if that's not too generic.

**Comment by mph-** [comment]
Well that turned out to be a lot harder than I thought.  Anyway, I've pushed a patch to master to control the component label style.  This is achieved with the `label_delimiter` attribute.
The default is `label_delimiter==`.  Your preferred style can be achieved with `label_delimiter=\\'.  You can also have the component name and component value on opposite sides of a component with `label_delimiter=a`.  See the new docs https://lcapy.readthedocs.io/en/latest/schematics.html :-)

**Comment by mph-** [comment]
After some thought, my proposed suggestion is flexible but not obvious.  I think I may add a `label_style` attribute with options `stacked`, `split`, and maybe `aligned` (default).  This could be extended with `name` to only show the component name, and `value` to only show the component value.

**Comment by timchinowsky** [comment]
Amazing, thank you, looks great!
